apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::476484257359:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4EO0U0V60WSZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::476484257359:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-07T14:54:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1501"
  uid: cd1fd28a-ed83-4887-851a-85519b82d98b
